### PR TITLE
Update to latest roborio toolchain 2022-1

### PR DESCRIPTION
**Pull request by agelsomini**

### CODE REVIEW

**Comment by virtuald** [comment]
Thanks for doing this! If you could add another commit to upgrade to python 3.10.1, that would be great. I can build the image later today and push it.

I wonder if we should be using github's docker repo instead of docker hub though, since they're being more stingy these days. Then we could build and push via github actions?

**Comment by agelsomini** [comment]
@virtuald Talk about being up to date.  3.10.1 was released today :)

I'm more than happy to look at switching to Github's docker repo.  Sounds like something to do after the first pass of upgrading RobotPy to 2022 is complete.

**Comment by virtuald** [comment]
You didn't update `os-release`.. has that changed in the latest beta image? I'm not sure it actually matters that much, but it would be good to be consistent.

You also didn't update `pip.conf`

**Comment by agelsomini** [comment]
> You didn't update `os-release`.. has that changed in the latest beta image? I'm not sure it actually matters that much, but it would be good to be consistent.
> 
> You also didn't update `pip.conf`

Not sure on os-release.  I'll need to flash my roborio to 2022 and check as I'm assuming that is a NI owned file based on the contents, I don't see it anywhere in the wpilib repos.

Updated pip.conf to 2022.  Out of curiosity is there a reason for this separation?  Is it just to make it less likely someone installs the wrong package?  I'm assuming that if all the dependencies are correct there is no real need to separate out the wheels by year.

**Comment by auscompgeek** [comment]
> I'll need to flash my roborio to 2022

It should be enough to just unpack the image and fish out the files. Last I checked it was just a tarball.

**Comment by virtuald** [comment]
The roborio installer grabs packages from that per-year directory. If for some reason a package is discontinued, a user might accidentally retrieve a discontinued package (via the installer) and not realize that it wouldn't work for this year. Additionally, version constraints from a prior year's package might cause a bunch of other packages from the prior year to be downloaded, which could cause pip to get really confused and give up.

Keeping packages separated by year makes it easier to manage this mess.

I'll take a look at the os-release file when I get home.

**Comment by virtuald** [comment]
Oh, the other reason to keep it separated is because when we're in the process of upgrading packages, it takes a couple of days to get through the upgrade process so there's a lot of different versions available. If roborio installer just downloaded from that URL, users still on the prior year might accidentally download new packages that aren't quite ready yet. In theory, version constraints could make this not occur, but once again it's just easier to not have to deal with it.

**Comment by agelsomini** [comment]
@virtuald Thanks for the explanation, that makes a lot of sense.

**Comment by agelsomini** [comment]
@virtuald Thanks for looking at os-release.  I missed that while our team has access to the beta release I didn't realize it was a separate download from NI that I didn't have.

**Comment by virtuald** [comment]
Thanks! Pushed the images.

**Pull request merged**
